import { createFileRoute, Link } from "@tanstack/react-router";
import { Badge } from "#/components/ui/badge";
import { Button } from "#/components/ui/button";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { getAllBlogPosts, getBlogBySlug, type BlogFrontmatter } from "#/lib/blog";
import { blogPost } from "#/lib/seo";

/* ─── Route ─────────────────────────────────────────────────────────── */

export const Route = createFileRoute("/blog/$slug")({
  head: ({ loaderData }) => {
    const post = loaderData as { slug: string; frontmatter: BlogFrontmatter } | undefined;
    const siteUrl = "https://gpui-query.freeoxide.com";
    if (!post) {
      return {
        meta: [{ title: "Not Found - gpui-query Blog" }],
      };
    }
    const fm = post.frontmatter;
    const url = `${siteUrl}/blog/${post.slug}`;
    // Per-post image generated by scripts/generate-og-images.ts
    // (runs during `bun run build`; rerun it after frontmatter changes).
    const ogImage = `${siteUrl}/og/blog/${post.slug}.png`;
    return {
      meta: [
        { title: `${fm.title} - gpui-query Blog` },
        { name: "description", content: fm.description },
        { property: "og:title", content: `${fm.title} - gpui-query Blog` },
        { property: "og:description", content: fm.description },
        { property: "og:type", content: "article" },
        { property: "og:url", content: url },
        { property: "og:image", content: ogImage },
        { property: "og:image:alt", content: `${fm.title} - gpui-query Blog` },
        { property: "article:author", content: fm.author },
        { property: "article:published_time", content: fm.date },
        { name: "twitter:card", content: "summary_large_image" },
        { name: "twitter:title", content: fm.title },
        { name: "twitter:description", content: fm.description },
        { name: "twitter:image", content: ogImage },
        ...(fm.tags ?? []).map((tag) => ({ property: "article:tag", content: tag })),
      ],
      links: [{ rel: "canonical", href: url }],
      scripts: [
        {
          type: "application/ld+json",
          children: JSON.stringify(
            blogPost({
              headline: fm.title,
              description: fm.description,
              author: fm.author,
              datePublished: fm.date,
              url,
              image: ogImage,
            }),
          ),
        },
      ],
    };
  },
  // Loader returns ONLY serializable data (slug + frontmatter). The MDX
  // `Content` component is non-serializable, so passing it through the loader
  // corrupts loaderData during prerender dehydrate/rehydrate (empty render +
  // hydration invariant). The component resolves `Content` itself below.
  loader: async ({ params }) => {
    const post = getBlogBySlug(params.slug);
    return post ? { slug: post.slug, frontmatter: post.frontmatter } : undefined;
  },
  component: BlogPostPage,
  notFoundComponent: PostNotFound,
});

/* ─── Helpers ───────────────────────────────────────────────────────── */

function formatDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

/* ─── Page ──────────────────────────────────────────────────────────── */

function BlogPostPage() {
  const data = Route.useLoaderData() as { slug: string; frontmatter: BlogFrontmatter } | undefined;
  if (!data) return <PostNotFound />;
  // Resolve the (non-serializable) MDX component at render time.
  const post = getBlogBySlug(data.slug);
  if (!post) return <PostNotFound />;

  const { Content, frontmatter } = post;
  const posts = getAllBlogPosts();
  const index = posts.findIndex((p) => p.slug === post.slug);
  const newer = index > 0 ? posts[index - 1] : undefined;
  const older = index >= 0 && index < posts.length - 1 ? posts[index + 1] : undefined;

  return (
    <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-16 lg:px-8">
      <Link
        to="/blog"
        className="inline-flex items-center text-sm font-medium text-muted-foreground transition-colors hover:text-primary"
      >
        <ArrowLeft className="mr-1.5 h-3.5 w-3.5" />
        Back to blog
      </Link>

      {/* Header */}
      <header className="mt-6 border-l-4 border-primary pl-5">
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{frontmatter.title}</h1>
        <p className="mt-3 text-lg text-muted-foreground">{frontmatter.description}</p>
        <div className="mt-4 flex flex-wrap items-center gap-3 text-sm text-muted-foreground">
          <span className="font-medium text-foreground/90">{frontmatter.author}</span>
          <span aria-hidden="true">·</span>
          <time dateTime={frontmatter.date}>{formatDate(frontmatter.date)}</time>
        </div>
        {frontmatter.tags && frontmatter.tags.length > 0 && (
          <div className="mt-3 flex flex-wrap gap-2">
            {frontmatter.tags.map((tag) => (
              <Badge key={tag} variant="secondary" className="font-normal">
                {tag}
              </Badge>
            ))}
          </div>
        )}
      </header>

      {/* Body */}
      <article className="prose prose-sm mt-10 max-w-none dark:prose-invert sm:prose-base">
        <Content />
      </article>

      {/* Prev / next nav */}
      <nav className="mt-16 flex flex-col gap-4 border-t border-border/60 pt-8 sm:flex-row sm:justify-between">
        {older ? (
          <Button variant="outline" asChild className="justify-start">
            <Link to="/blog/$slug" params={{ slug: older.slug }}>
              <ArrowLeft className="mr-2 h-4 w-4 shrink-0" />
              <span className="flex flex-col items-start truncate">
                <span className="text-[11px] uppercase tracking-wider text-muted-foreground">
                  Older
                </span>
                <span className="truncate">{older.frontmatter.title}</span>
              </span>
            </Link>
          </Button>
        ) : (
          <span className="hidden sm:block" />
        )}
        {newer ? (
          <Button variant="outline" asChild className="justify-end text-right">
            <Link to="/blog/$slug" params={{ slug: newer.slug }}>
              <span className="flex flex-col items-end truncate">
                <span className="text-[11px] uppercase tracking-wider text-muted-foreground">
                  Newer
                </span>
                <span className="truncate">{newer.frontmatter.title}</span>
              </span>
              <ArrowRight className="ml-2 h-4 w-4 shrink-0" />
            </Link>
          </Button>
        ) : null}
      </nav>
    </div>
  );
}

/* ─── 404 ───────────────────────────────────────────────────────────── */

function PostNotFound() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-24 lg:px-8">
      <div className="flex flex-col items-center text-center">
        <h1 className="text-2xl font-bold tracking-tight">Post not found</h1>
        <p className="mt-2 max-w-md text-muted-foreground">
          The article you are looking for does not exist or has been moved.
        </p>
        <Button asChild className="mt-6">
          <Link to="/blog">
            <ArrowLeft className="mr-2 h-4 w-4" />
            All posts
          </Link>
        </Button>
      </div>
    </div>
  );
}
