import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: 'gpui-query Docs',
  tagline: 'Zero-boilerplate async state management for GPUI',
  url: 'https://gpui-query.freeoxide.com',
  baseUrl: '/docs/',
  // Emit flat files (page.html, served at /page) instead of directory
  // indexes. Keeps served URLs identical to the canonical/sitemap URLs,
  // which never use a trailing slash. See web/vite.config.ts for the same
  // fix on the app side.
  trailingSlash: false,
  favicon: 'img/favicon.ico',
  clientModules: ['./src/firebaseAnalytics.ts'],

  future: {
    v4: true,
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Site-wide og:image fallback for docs pages. Generated by
    // web/scripts/generate-og-images.ts into static/img (runs before the
    // Docusaurus build in web's build chain). Individual docs can override
    // it with `image:` frontmatter.
    image: "img/og-docs.png",
    colorMode: {
      respectPrefersColorScheme: true,
      defaultMode: 'light',
    },
    navbar: {
      title: 'gpui-query',
      logo: {
        alt: 'gpui-query',
        src: 'img/logo.svg',
        // Points at the marketing homepage at the domain root `/`, which is a
        // separate app served outside the docs `/docs/` baseUrl. Docusaurus's
        // <Link> always re-appends baseUrl to root-absolute hrefs (even the
        // `pathname://` escape hatch does), which would turn this into `/docs/`.
        // The Logo component is swizzled (src/theme/Logo) to render a plain <a>
        // that escapes the baseUrl — see that file for the full explanation.
        href: '/',
        target: '_self',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Docs',
        },
        {
          href: 'https://github.com/freeoxide/gpui-query',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Getting Started',
              to: '/getting-started/installation',
            },
            {
              label: 'API Reference',
              to: '/api/queries',
            },
            {
              label: 'Guides',
              to: '/guides/caching',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/freeoxide/gpui-query',
            },
          ],
        },
      ],
      copyright: 'Copyright &copy; 2024-2026 hmziqrs.',
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['rust', 'toml'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
